<?php
while(true)
echo "hellolonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonhellonheln";

?>